#%RAML 1.0 DataType
displayName: Customer
description: Customer Response Object
type: !include customerBase.raml

properties:
  customerId:
    type: string
    minLength: 1
    example: 4d4de7d6-7f5e-4778-9c70-babba6c25c55